# This is a basic workflow to help you get started with Actions

name: CI Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # It is required for posting Pull Request comment.
      contents: read       # It is required for checking out the code in GitHub Action.
    container:
      image: codetyio/codety:0.002
    steps:
      - run: ls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  checkout:
#    # The type of runner that the job will run on
#    runs-on: self-hosted
#
#    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
##      - uses: actions/checkout@v4
#      # Runs a set of commands using the runners shell
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
