name: Codety
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    container:
      image: codetyio/codety:0.02
    steps:
      - run: ls -ls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

